<?php

use App\Profile;
use Faker\Generator as Faker;

$factory->define(Profile::class, function (Faker $faker) {
    return [
        'user_id' => 1,
        'visit_call' => 'visit_call',
        'mark_in_lat' => 'mark_in_lat',
        'mark_in_lng' => 'mark_in_lng',
        'mark_out_lat' => 'mark_out_lat',
        'mark_out_lng' => 'mark_out_lng',
        'date' => 'date',
        'mobile_1' => 1,
        'email_1' => 'email_1',
        'photo_1_path' => 'photo_1_path',
        'company_name' => 'company_name',
        'industry' => 'industry',
        'employee_size' => 'employee_size',
        'turnover' => 'turnover',
        'head_office' => 'head_office',
        'address' => 'address',
        'website' => 'website',
        'contact_1_mobile' => 1,
        'contact_1_email' => 'contact_1_email',
        'contact_2_mobile' => 1,
        'contact_2_email' => 'contact_2_email',
        'contact_1_name' => 'contact_1_name',
        'contact_2_name' => 'contact_2_name',
        'product_offered' => 'product_offered',
        'deal_date' => 'deal_date',
        'agreement_date' => 'agreement_date',
        'terms' => 'terms',
        'remarks' => 'remarks',
        'next_meeting_date' => 'next_meeting_date',
        'is_active' => true,
        'is_deleted' => false,
        'service_fees' => 'service_fees',
        'recruitment_fees' => 'recruitment_fees',
        'onboarding_fees' => 'onboarding_fees',
        'service_fee_on_reimbursements' => 'service_fee_on_reimbursements',
        'service_fee_on_incentive' => 'service_fee_on_incentive',
        'service_fee_on_ad_hoc' => 'service_fee_on_ad_hoc',
        'absorption_fee' => 'absorption_fee',
        'agency_fee_for_junior_level' => 'agency_fee_for_junior_level',
        'agency_fee_for_middle_level' => 'agency_fee_for_middle_level',
        'agency_fee_for_senior_level' => 'agency_fee_for_senior_level',
        'hajiri_per_user_per_month' => 'hajiri_per_user_per_month',
        'dastavej_per_user_per_month' => 'dastavej_per_user_per_month',
        'sales_per_user_per_month' => 'sales_per_user_per_month',
        'merchandising_per_user_per_month' => 'merchandising_per_user_per_month',
        'mark_in_address' => 'mark_in_address',
        'mark_out_address' => 'mark_out_address',
    ];
});
