<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CrudeFocusedTarget extends Model
{
    protected $fillable = [
        'region',
        'channel',
        'chain_name',
        'billing_code',
        'store_code',
        'store_name',
        'location',
        'city',
        'state',
        'rsm',
        'asm',
        'supervisor_code',
        'supervisor_name',
        'brand',
        'ba_status',
        'store_status', //User Data
        'month',
        'year',
        'target',
        'achieved',
        'baby', // category
        'baby_Kit',
        'baby_Oil',
        'bath_salt',
        'bathing',
        'body',
        'body_butter',
        'body_cream',
        'body_lotion',
        'body_scrub',
        'body_wash',
        'capsules',
        'cleanser',
        'cleansing',
        'combo_kit',
        'conditioner',
        'cream',
        'diaper',
        'dusting_powder',
        'face_cream',
        'face_free',
        'face_Mask',
        'face_Milk',
        'face_scrub',
        'face_Serum',
        'face_Spot',
        'face_toner',
        'facewash',
        'freebies',
        'gel',
        'gift_pack',
        'hair_care',
        'hair_Mask',
        'hair_Oil',
        'hair_Serum',
        'hand_cream',
        'hygine',
        'kajal',
        'kids_body',
        'lip_balm',
        'lotion',
        'mask',
        'moisturizer',
        'mosquito_protection',
        'oil',
        'oral',
        'otc',
        'peeling',
        'serum',
        'shampoo',
        'sheet_mask',
        'sub_cat',
        'sun_cat',
        'sun_care',
        'sunscreen',
        'tablets',
        'toner',
        'yogurt_for',
    ];
}
